//
//  loggerTests.m
//  Tests of the WeblogNG Logger library for iOS.
//
//  Created by Stephen Kuenzli on 11/23/13.
//  Copyright (c) 2013, 2014 WeblogNG. All rights reserved.
//

#import <XCTest/XCTest.h>
#import <OCMock/OCMock.h>

#define HC_SHORTHAND

#import <OCHamcrest/OCHamcrest.h>

#import "logger.h"

static const int TIMING_THRESHOLD_FOR_NOW_IN_MS = 25;
static const int TIMING_THRESHOLD_FOR_NOW_IN_S = 2;

double epochTimeInMilliseconds() {
    return [[NSDate date] timeIntervalSince1970] * 1000;
}


@interface WNGLoggerTests : XCTestCase

@end

@implementation WNGLoggerTests

WNGLogger *logger;
NSString *apiHost;
NSString *apiKey;
id mockApiConnection;

- (void)setUp {
    [super setUp];
    
    apiHost = @"api.weblogng.com";
    apiKey = @"93c5a127-e2a4-42cc-9cc6-cf17fdac8a7f";
 
    logger = [[WNGLogger alloc] initWithConfig:apiHost apiKey:apiKey];

    mockApiConnection = [OCMockObject mockForClass:[WNGLoggerAPIConnection class]];
    logger.apiConnection = mockApiConnection;
}

- (void)tearDown {
    [super tearDown];
}

- (void)test_defaultState_of_Logger {
    WNGLogger *logger = [[WNGLogger alloc] init];

    assertThat(logger.apiHost, is(nilValue()));
    assertThat(logger.apiKey, is(nilValue()));
    assertThat(logger.apiConnection, is(nilValue()));
}

- (void)test_Logger_properties {
    WNGLogger *logger = [[WNGLogger alloc] init];
    NSString *expectedApiHost = @"api.weblogng.com";
    NSString *expectedApiKey = @"api-key-56789";
    WNGLoggerAPIConnection *expectedApiConnection = [OCMockObject mockForClass:[WNGLoggerAPIConnection class]];

    logger.apiHost = expectedApiHost;
    logger.apiKey = expectedApiKey;
    logger.apiConnection = expectedApiConnection;
    
    assertThat(logger.apiHost, equalTo(expectedApiHost));
    assertThat(logger.apiKey, equalTo(expectedApiKey));
    assertThat(logger.apiConnection, equalTo(expectedApiConnection));
}

- (void)test_Logger_prints_property_data_in_description {
    NSString *description = logger.description;
    assertThat(description, containsString(logger.apiHost));
    assertThat(description, containsString(logger.apiKey));
}

- (void)test_initWithConfig_initializes_the_logger_with_configuration {
    NSString *expectedHost = @"host";
    NSString *expectedKey = @"key";

    WNGLogger *logger = [[WNGLogger alloc] initWithConfig:expectedHost apiKey:expectedKey];

    assertThat(logger.apiHost, equalTo(expectedHost));
    assertThat(logger.apiKey, equalTo(expectedKey));
    assertThat(logger.apiConnection, isNot(nil));
}

- (void)test_convertToMetricMessage_constructs_a_proper_metric {
    
    NSString *metricName = [NSString stringWithFormat: @"metricName_%d", arc4random_uniform(10)];
    NSNumber *metricValue = [NSNumber numberWithDouble: arc4random_uniform(10)];
    
    NSString *message = [WNGLogger convertToMetricMessage: apiKey metricName:metricName metricValue:metricValue];
    
    NSArray *tokens = [message componentsSeparatedByString: @" "];
    
    //should look like:
    //v1.metric 93c5a127-e2a4-42cc-9cc6-cf17fdac8a7f metricName_8 3 1388529207
    //NSLog(@"actual message generated by convertToMetricMessage:\n%@", message);
    
    assertThat([NSNumber numberWithInt:(uint32_t) [tokens count]], equalToInt(5));
    assertThat(tokens[0], equalTo(@"v1.metric"));
    assertThat(tokens[1], equalTo(apiKey));
    assertThat(tokens[2], equalTo(metricName));
    assertThat(tokens[3], equalTo([metricValue stringValue]));
    
    double timestamp = [tokens[4] doubleValue];
    double now = (epochTimeInMilliseconds()) / 1000;
    assertThatLongLong(timestamp, closeTo(now, TIMING_THRESHOLD_FOR_NOW_IN_S));
}

- (void)test_sendMetric_sends_reasonable_messages_to_connection {
    NSString *metricName = @"metricName";
    NSNumber *metricValue = [NSNumber numberWithDouble:1234.5];
    NSString *nowStr = [[WNGTime epochTimeInMilliseconds] stringValue];
    NSString *mostSignificantBitsOfNow = [nowStr substringToIndex:8];
    
    NSString *expectedMessage = [NSString stringWithFormat: @"v1.metric %@ %@ %@ %@",
                                 [logger apiKey], metricName, [metricValue stringValue], mostSignificantBitsOfNow];
    
    [[mockApiConnection expect] sendMetric:startsWith(expectedMessage)];

    [logger sendMetric:metricName metricValue:metricValue];
    
    [mockApiConnection verify];
}

- (void)test_sendMetric_allows_a_metricValue_of_zero {
    NSString *metricName = @"metricName.value.is.zero";
    NSNumber *metricValue = [NSNumber numberWithInt:0];
    
    NSString *expectedMessage = [NSString stringWithFormat: @"v1.metric %@ %@ %@",
                                 [logger apiKey], [WNGLogger sanitizeMetricName:metricName], [metricValue stringValue]];
    
    [[mockApiConnection expect] sendMetric:startsWith(expectedMessage)];
    
    [logger sendMetric:metricName metricValue:metricValue];
    
    [mockApiConnection verify];
}

- (void)test_sendMetric_sanitizes_metrics_before_sending {
    NSString *metricName = @"metricName.needs$sanitization";
    NSNumber *metricValue = [NSNumber numberWithDouble:1234.5];
    
    NSString *expectedMessage = [NSString stringWithFormat: @"v1.metric %@ %@ %@",
                                 [logger apiKey], [WNGLogger sanitizeMetricName:metricName], [metricValue stringValue]];

    [[mockApiConnection expect] sendMetric:startsWith(expectedMessage)];

    [logger sendMetric:metricName metricValue:metricValue];
    
    [mockApiConnection verify];
}


- (void)test_sanitizeMetricName_sanitizes_invalid_names {
    for(NSString *forbiddenChar in @[@".", @"!", @"," , @";", @":", @"?", @"/", @"\\", @"@", @"#", @"$", @"%", @"^", @"&", @"*", @"(", @")"]){
        NSString *actualMetricName = [WNGLogger sanitizeMetricName: [NSString stringWithFormat:@"metric-name_1%@2", forbiddenChar]];
        assertThat(actualMetricName, equalTo(@"metric-name_1_2"));
    }
}

- (void)test_convertToMetricName_builds_a_metric_name_from_provided_request_GET {
    NSURLRequest *req = [[NSURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://api.weblogng.com/some/service"]];
    NSString *actualMetricName = [WNGLogger convertToMetricName:req];
    
    assertThat(actualMetricName, equalTo(@"api_weblogng_com-GET"));
}

- (void)test_convertToMetricName_builds_a_metric_name_from_provided_request_POST {
    NSMutableURLRequest *req = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:@"https://t.co"]];
    [req setHTTPMethod:@"POST"];
    
    NSString *actualMetricName = [WNGLogger convertToMetricName:req];
    
    assertThat(actualMetricName, equalTo(@"t_co-POST"));
}

- (void)test_convertToMetricName_handles_nil_requests {
    assertThat([WNGLogger convertToMetricName:nil], equalTo(@"unknown"));
}

- (void)test_recordStart_creates_a_timer_and_starts_it {
    WNGTimer *timer = [logger recordStart: @"metric_name"];
    assertThat(timer.tStart, closeTo(epochTimeInMilliseconds(), TIMING_THRESHOLD_FOR_NOW_IN_MS));
}

- (void)test_hasTimer_for_metric_name_returns_false_when_timer_does_not_exist {
    assertThatBool([logger hasTimerFor: @"does not exist"], equalToBool(FALSE));
}

- (void)test_timerCount_reports_the_correct_number_of_timers_in_progress {
    u_int32_t expectedTimerCount = arc4random_uniform(1000);

    for(int i = 0; i<expectedTimerCount; i++){
        [logger recordStart:[NSString stringWithFormat:@"metric_%d", i]];
    }

    assertThatUnsignedInteger([logger timerCount], equalToUnsignedInt(expectedTimerCount));

}

- (void)test_hasTimer_for_metric_name_returns_true_when_timer_does_exist {
    NSString *metricName = @"metric_that_exists";
    [logger recordStart:metricName];
    assertThatBool([logger hasTimerFor: metricName], equalToBool(TRUE));
}

- (void)test_recordFinish_records_the_current_time_when_called_for_a_given_metric_name {
    NSString *metricName = @"metric_name";
    WNGTimer *startedTimer = [logger recordStart:metricName];
    WNGTimer *finishedTimer = [logger recordFinish:metricName];

    assertThat(finishedTimer, equalTo(startedTimer));
    assertThat(finishedTimer, isNot(nil));
    assertThat(finishedTimer.tFinish, closeTo(epochTimeInMilliseconds(), TIMING_THRESHOLD_FOR_NOW_IN_MS));
}

- (void)test_recordFinishAndSendMetric_should_call_recordFinish_and_sendMetric {
    NSString *metricName = @"metric.recordFinishAndSend";
    [logger recordStart:metricName];

    NSString *expectedMessage = [NSString stringWithFormat: @"v1.metric %@ %@",
                    [logger apiKey],
                    [WNGLogger sanitizeMetricName:metricName]];

    [[mockApiConnection expect] sendMetric:startsWith(expectedMessage)];

    WNGTimer *timer = [logger recordFinishAndSendMetric:metricName];

    [mockApiConnection verify];

    assertThatBool([logger hasTimerFor: metricName], equalToBool(FALSE));
    assertThat(timer.tStart, closeTo(epochTimeInMilliseconds(), TIMING_THRESHOLD_FOR_NOW_IN_MS));
    assertThat(timer.tFinish, closeTo(epochTimeInMilliseconds(), TIMING_THRESHOLD_FOR_NOW_IN_MS));
    assertThat(timer.elapsedTime, closeTo(0, TIMING_THRESHOLD_FOR_NOW_IN_MS));
}

- (void)test_executeWithTiming_should_call_recordStart_invoke_provided_block_and_then_recordFinishAndSendMetric {
    NSString *metricName = @"metric.executeWithTiming";
    
    NSString *expectedMessage = [NSString stringWithFormat: @"v1.metric %@ %@",
                                 [logger apiKey],
                                 [WNGLogger sanitizeMetricName:metricName]];
    
    double tStart = epochTimeInMilliseconds();
    
    [[mockApiConnection expect] sendMetric:startsWith(expectedMessage)];
    
    WNGTimer *timer = [logger executeWithTiming:metricName aBlock: ^{
        for (int i = 0; i < 10; i++) {
            [NSThread sleepForTimeInterval:0.1];
        }
    }];

    
    [mockApiConnection verify];
    
    double tFinish = epochTimeInMilliseconds();
    
    assertThatBool([logger hasTimerFor: metricName], equalToBool(FALSE));
    assertThat(timer.tStart, closeTo(tStart, TIMING_THRESHOLD_FOR_NOW_IN_MS));
    assertThat(timer.tFinish, closeTo(tFinish, TIMING_THRESHOLD_FOR_NOW_IN_MS));
    assertThat(timer.elapsedTime, closeTo(tFinish - tStart, TIMING_THRESHOLD_FOR_NOW_IN_MS));
    
    NSLog(@"elapsedTime for executing block: %@ms", timer.elapsedTime);
}


/**
 * test the full lifecycle of the sharedLogger so that temporal effects are simpler to deal with.
 */
- (void)test_full_lifecycle_of_sharedLogger {
    //test initial state, init, and reset
    assertThat([WNGLogger sharedLogger], is(nilValue()));

    WNGLogger *logger = [WNGLogger initSharedLogger:apiKey];
    assertThat([logger apiHost], isNot(nil));
    assertThat([logger apiKey], equalTo(apiKey));
    
    [WNGLogger resetSharedLogger];
    assertThat([WNGLogger sharedLogger], is(nilValue()));
    
    //test repeated calls to init return the same logger
    logger = [WNGLogger initSharedLogger:apiKey];
    assertThat(logger, equalTo([WNGLogger initSharedLogger:apiKey]));
}

@end

@interface WNGTimeTests : XCTestCase

@end

@implementation WNGTimeTests

- (void)test_getEpochTimeInMilliseconds {
    NSNumber *actualTime = [WNGTime epochTimeInMilliseconds];
    double now = epochTimeInMilliseconds();

    assertThat(actualTime, closeTo(now, TIMING_THRESHOLD_FOR_NOW_IN_MS));
}

- (void)test_getEpochTimeInSeconds {
    NSNumber *actualTime = [WNGTime epochTimeInSeconds];
    double now = (epochTimeInMilliseconds()) / 1000;
    
    assertThat(actualTime, closeTo(now, TIMING_THRESHOLD_FOR_NOW_IN_S));

}

@end

@interface WNGTimerTests : XCTestCase

@end

@implementation WNGTimerTests

WNGTimer *timer;

- (void)setUp {
    [super setUp];

    timer = [[WNGTimer alloc] init];
    
}

- (void)test_default_state_of_Timer {
    assertThat(timer.tStart, is(nilValue()));
    assertThat(timer.tFinish, is(nilValue()));
}

- (void)test_start_method_records_start_time {
    [timer start];
    assertThat(timer.tStart, closeTo([[WNGTime epochTimeInMilliseconds] doubleValue], TIMING_THRESHOLD_FOR_NOW_IN_MS));
}

- (void)test_finish_method_records_finish_time {
    [timer finish];
    assertThat(timer.tFinish, closeTo([[WNGTime epochTimeInMilliseconds] doubleValue], TIMING_THRESHOLD_FOR_NOW_IN_MS));
}

- (void)test_elapsedTime_is_computed_from_tStart_and_tFinish {
    [timer init:[NSNumber numberWithLong:42] tFinish:[NSNumber numberWithLong: 100]];

    assertThat([timer elapsedTime], equalTo([NSNumber numberWithLong: 58]));
}

@end

